brew install slack
brew install zoom
brew install iterm2
brew install google-chrome
brew install firefox
brew install visual-studio-code
brew install sublime-text
brew install sublime-merge
brew install sequel-ace
brew install postico
brew install postman
brew install cyberduck
brew install tunnelblick
