brew install the_silver_searcher
brew install speedtest-cli
brew install vim
brew install neovim
brew install zsh
brew install liquidprompt
brew install aria2
brew install wget
brew install tree
brew install jq
brew install ack
brew install cmake
brew install cowsay
brew install tmux
brew install lynx
#brew install nmap
brew install binutils
brew install inetutils
brew install htop
brew install cloc
brew install coreutils
brew install findutils
brew install readline
#brew install lua
brew install moreutils
brew install mc
brew install screen
brew install gh
brew install elinks
brew install git
brew install fzf
#brew install awscli
brew install ansible
brew install bat
brew install exa
brew install git-delta
brew install tldr
brew install glances
brew install procs
#brew install httpie
brew install ncdu
brew install duf
#brew install zoxide
