brew install zsh
brew install neovim
brew install vim
brew install git
brew install gh
brew install liquidprompt
brew install fzf
brew install ripgrep

brew install binutils
brew install inetutils
brew install coreutils
brew install findutils
brew install moreutils
brew install readline
brew install reattach-to-user-namespace
brew install tmux
brew install screen

#brew install awscli
brew install ansible
brew install aria2
brew install wget
brew install tree
brew install jq
brew install ack
brew install cmake
brew install cowsay
brew install htop
brew install cloc
brew install mc
brew install bat
brew install exa
brew install git-delta
brew install tldr
brew install glances
brew install procs

#brew install ncdu
#brew install duf
#brew install lynx
#brew install nmap
